"""Add mac_address to assets

Revision ID: 6f03f254e8cd
Revises: 4df5bad16769
Create Date: 2026-08-31 19:47:52.548708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f03f254e8cd'
down_revision: Union[str, None] = '4df5bad16769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('mac_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'mac_address')
    # ### end Alembic commands ###
