"""add_scanner_engines

Revision ID: a93e432317eb
Revises: a550e29e2d1a
Create Date: 2026-08-31 16:01:00.066081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a93e432317eb'
down_revision: Union[str, None] = 'a550e29e2d1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    scanner_engine_enum = postgresql.ENUM('OPENVAS', 'NMAP', 'NUCLEI', 'NESSUS', name='scannerengine')
    scanner_engine_enum.create(op.get_bind(), checkfirst=True)
    
    op.add_column('scans', sa.Column('scanner_engine', scanner_engine_enum, nullable=False, server_default='OPENVAS'))
    op.add_column('vulnerabilities', sa.Column('source_engine', sa.String(), nullable=False, server_default='OPENVAS'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vulnerabilities', 'source_engine')
    op.drop_column('scans', 'scanner_engine')
    op.execute("DROP TYPE IF EXISTS scannerengine")
    # ### end Alembic commands ###
