"""add ai_analysis to vulnerabilities

Revision ID: e123a3b61bf0
Revises: d9129a3b61bf
Create Date: 2026-09-20 01:52:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e123a3b61bf0'
down_revision = 'd9129a3b61bf'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vulnerabilities', sa.Column('ai_analysis', sa.JSON(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vulnerabilities', 'ai_analysis')
    # ### end Alembic commands ###
